adds isNumber helper
wertschoepfer/ws-skript pull request #6
Opened 2021-07-08 07:49 UTC by ws-lucas

2021-07-08 08:13 UTC, ws-thomas requested changes
> `number` is not defined
außerdem coerced isNaN den eingegebenen Wert zu einer Number, deswegen sind die folgenden "Testfälle" auch `true`:
```js
WS.isNumber("123");
WS.isNumber({ toString() { return 123; } });
WS.isNumber({ valueOf() { return 123; } });
WS.isNumber(true);
WS.isNumber(false);
```
warum eine extra Helperfunktion und nicht einfach `typeof num === 'number'`? it's quick, it's easy and it's free, TypeScript versteht es, man braucht kein WS-Skript, es ist schneller, etc pp

2021-07-09 08:08 UTC, ws-lucas commented
Achso. Ich wollte `isNaN()` eigentlich nur sinnvoll erweitern und ins Skript packen, aber in dem Fall isses ja dann falsch. 
Was ist wenn wir stattdessen deinen Vorschlag einbauen? Also:
```
isNumber: function(num) {
  return typeof num === 'number';
}
```

2021-07-09 10:06 UTC, ws-thomas commented
Was möchtest du mit der Funktion `isNumber()` genau testen? Aktuell testet sie, ob eine Variable zu einer Nummer umgewandelt tatsächlich auch als Nummer benutzt werden kann und nicht durch NaN irgendwelche Rechnungen unbrauchbar macht. Mein Vorschlag dagegen würde überprüfen, ob die Variable an sich vom Datentyp Number ist, egal ob NaN, Infinity, 0, Ganzzahl oder Gleitkommazahl.

Es gibt mit `typeof x === 'number'`, `Number.isFinite()`, `Number.isInteger()`, `isNaN()`, `Number.isNaN()` etc. genug Wege, mit JS-Bordmitteln genaue Aussagen zu einer Variable zu treffen. Daher die Frage, was soll `WS.isNumber()` machen, was JS nicht von Haus aus mit vergleichbar vielen geschriebenen Zeichen kann?

2021-07-09 10:25 UTC, ws-lucas commented
Prinzipiell soll die Methode einfach nur überprüfen, ob mit dem übergebenen Wert auch vernünftig weitere Berechnungen durchgeführt werden können. Also ob der Wert eine Zahl (isNumber) ist. Da die übergebenen Werte auch meistens aus (JobRouter) Inputfeldern stammen, kann es sich hierbei auch durchaus um Zahlen im Stringformat handeln.
Ich dachte es wäre praktisch eine kurze Methode dafür anzusetzen, anstatt im Code zig Vergleiche durchzuführen.

2021-07-09 10:33 UTC, ws-thomas commented
Dann muss sichergestellt sein, dass es sich um eine Zahl handelt, ansonsten gibt es bei `WS.isNumber("123")` schon wieder Stringkonkatenation statt Addition 😄 Das Ding ist, dass auch wenn ein Zahlenstring eine "gescheite" Zahl darstellt, er zuerst zu einer Number konvertiert werden muss (z.B. `Number(x)` oder `+x`). Also wäre für den genannten Anwendungsfall meiner Meinung nach entweder `Number.isFinite()` (alle Zahlen außer +-Infinity und NaN) oder `typeof x === 'number' && !isNaN(x)` geeignet. Für letzteres wäre eine Helferfunktion sinnvoll, für ersteres... kommt drauf an, ob die Kollegen lieber "WS-Skript" oder "JavaScript" lernen wollen 😄

2021-07-09 10:35 UTC, ws-thomas commented
Wie dem auch sei, einem Merge steht zumindest noch der Fehler, dass die Variable `number` nicht existiert, entgegen

2021-07-09 12:11 UTC, closed without merging

2021-07-09 12:12 UTC, ws-lucas commented
Benutzt Boardmittel.